config/routes.rb
Rails.application.routes.draw do

  #sessions
  get "/login", to: "sessions#new", as: :login
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :subjects
  resources :classrooms
  resources :books
  resources :buses
  resources :stages, only: [:index, :show, :edit]
  resources :teachers
  resources :parents
  resources :students

  #users
  get "/", to: "sessions#new"
  # get "/users/:id", to: "users#show", as: :my_profile
  # get "/my_profile", to: "users#show", as: :my_profile

  #dashboard
  get "/dashboard/parents", to: "dashboard_parents#index", as: :dashboard_parents

  get "/dashboard/students", to: "dashboard_students#index", as: :dashboard_students

  #books
  resources :books, except: [:show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/home/_footer.html.erb
 <footer class="footer-wrap-layout1">
            <div class="copyright">© Copyrights <a href="#">akkhor</a> 2019. All rights reserved. Designed by <a href="#">PsdBosS</a></div>
        </footer>

app/views/home/_header.html.erb
<div class="navbar navbar-expand-md header-menu-one bg-light">
  <div class="nav-bar-header-one">
    <div class="header-logo">
      <a href="<%= users_path%>">
        <img src="/img/logo.png" alt="logo">
      </a>
    </div>
    <div class="toggle-button sidebar-toggle">
      <button type="button" class="item-link">
        <span class="btn-icon-wrap">
          <span></span>
          <span></span>
          <span></span>
        </span>
      </button>
    </div>
  </div>
  <div class="d-md-none mobile-nav-bar">
    <button class="navbar-toggler pulse-animation" type="button" data-toggle="collapse" data-target="#mobile-navbar" aria-expanded="false">
      <i class="far fa-arrow-alt-circle-down"></i>
    </button>
    <button type="button" class="navbar-toggler sidebar-toggle-mobile">
      <i class="fas fa-bars"></i>
    </button>
  </div>
  <div class="header-main-menu collapse navbar-collapse" id="mobile-navbar">
    <ul class="navbar-nav">
      <li class="navbar-item header-search-bar">
        <div class="input-group stylish-input-group">
          <span class="input-group-addon">
            <button type="submit">
              <span class="flaticon-search" aria-hidden="true"></span>
            </button>
          </span>
          <input type="text" class="input-search form-control" placeholder="Find Something . . .">
        </div>
      </li>
    </ul>
    <ul class="navbar-nav">
      <li class="navbar-item dropdown header-admin">
        <a class="navbar-nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
          <div class="admin-title">
            <h5 class="item-title"> <%= current_user.name.titleize if current_user.present? %></h5>
            <span><%= current_user.role.name.capitalize if current_user.present? %></span>
          </div>
          <div class="admin-img">
            <img src="/img/figure/admin.jpg" alt="Admin">
          </div>
        </a>
        <div class=" dropdown-menu dropdown-menu-right">
          <div class="item-header">
            <h6 class="item-title"> <%= current_user.name.titleize if current_user.present? %></h6>
          </div>
          <% if current_user.present?%>
            <div class="item-content">
              <ul class="settings-list">
                <li><a href="<%= user_path(current_user)%>"><i class="flaticon-user"></i>My Profile</a></li>
                <li><a href="#"><i class="flaticon-list"></i>Task</a></li>
                <li><a href="#"><i class="flaticon-chat-comment-oval-speech-bubble-with-text-lines"></i>Message</a></li>
                <li><a href="<%= edit_user_path(current_user)%>"><i class="flaticon-gear-loading"></i>Account Settings</a></li>
                <li><a href="<%= login_path %>"><i class="flaticon-turn-off"></i>Log Out</a></li>
              </ul>
            </div>
          <%end%>
        </div>
      </li>
      <li class="navbar-item dropdown header-message">
        <a class="navbar-nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
          <i class="far fa-envelope"></i>
          <div class="item-title d-md-none text-16 mg-l-10">Message</div>
          <span>5</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right">
          <div class="item-header">
            <h6 class="item-title">05 Message</h6>
          </div>
          <div class="item-content">
            <div class="media">
              <div class="item-img bg-skyblue author-online">
                <img src="/img/figure/student11.png" alt="/img">
              </div>
              <div class="media-body space-sm">
                <div class="item-title">
                  <a href="#">
                    <span class="item-name">Maria Zaman</span>
                    <span class="item-time">18:30</span>
                  </a>
                </div>
                <p>What is the reason of buy this item.
                  Is it usefull for me.....</p>
              </div>
            </div>
            <div class="media">
              <div class="item-img bg-yellow author-online">
                <img src="/img/figure/student12.png" alt="/img">
              </div>
              <div class="media-body space-sm">
                <div class="item-title">
                  <a href="#">
                    <span class="item-name">Benny Roy</span>
                    <span class="item-time">10:35</span>
                  </a>
                </div>
                <p>What is the reason of buy this item.
                  Is it usefull for me.....</p>
              </div>
            </div>
            <div class="media">
              <div class="item-img bg-pink">
                <img src="/img/figure/student13.png" alt="/img">
              </div>
              <div class="media-body space-sm">
                <div class="item-title">
                  <a href="#">
                    <span class="item-name">Steven</span>
                    <span class="item-time">02:35</span>
                  </a>
                </div>
                <p>What is the reason of buy this item.
                  Is it usefull for me.....</p>
              </div>
            </div>
            <div class="media">
              <div class="item-img bg-violet-blue">
                <img src="/img/figure/student11.png" alt="/img">
              </div>
              <div class="media-body space-sm">
                <div class="item-title">
                  <a href="#">
                    <span class="item-name">Joshep Joe</span>
                    <span class="item-time">12:35</span>
                  </a>
                </div>
                <p>What is the reason of buy this item.
                  Is it usefull for me.....</p>
              </div>
            </div>
          </div>
        </div>
      </li>
      <li class="navbar-item dropdown header-notification">
        <a class="navbar-nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
          <i class="far fa-bell"></i>
          <div class="item-title d-md-none text-16 mg-l-10">Notification</div>
          <span>8</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right">
          <div class="item-header">
            <h6 class="item-title">03 Notifiacations</h6>
          </div>
          <div class="item-content">
            <div class="media">
              <div class="item-icon bg-skyblue">
                <i class="fas fa-check"></i>
              </div>
              <div class="media-body space-sm">
                <div class="post-title">Complete Today Task</div>
                <span>1 Mins ago</span>
              </div>
            </div>
            <div class="media">
              <div class="item-icon bg-orange">
                <i class="fas fa-calendar-alt"></i>
              </div>
              <div class="media-body space-sm">
                <div class="post-title">Director Metting</div>
                <span>20 Mins ago</span>
              </div>
            </div>
            <div class="media">
              <div class="item-icon bg-violet-blue">
                <i class="fas fa-cogs"></i>
              </div>
              <div class="media-body space-sm">
                <div class="post-title">Update Password</div>
                <span>45 Mins ago</span>
              </div>
            </div>
          </div>
        </div>
      </li>
      <li class="navbar-item dropdown header-language">
        <a class="navbar-nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false"><i class="fas fa-globe-americas"></i>EN</a>
        <div class="dropdown-menu dropdown-menu-right">
          <a class="dropdown-item" href="#">English</a>
          <a class="dropdown-item" href="#">Spanish</a>
          <a class="dropdown-item" href="#">Franchis</a>
          <a class="dropdown-item" href="#">Chiness</a>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/home/_sidebar.html.erb
<div class="sidebar-main sidebar-menu-one sidebar-expand-md sidebar-color">
  <div class="mobile-sidebar-header d-md-none">
    <div class="header-logo">
      <a href="<%= users_path %>"><img src="/img/logo1.png" alt="logo"></a>
    </div>
  </div>
  <div class="sidebar-menu-content">
    <ul class="nav nav-sidebar-menu sidebar-toggle-view">
      <li class="nav-item sidebar-nav-item">
        <a href="#" class="nav-link"><i class="flaticon-dashboard"></i><span>Dashboard</span></a>
        <ul class="nav sub-group-menu">
          <li class="nav-item">
            <a href="index.html" class="nav-link"><i class="fas fa-angle-right"></i>Admin</a>
          </li>
          <li class="nav-item">
            <a href="<%= dashboard_students_path %>" class="nav-link"><i class="fas fa-angle-right"></i>Students</a>
          </li>
          <li class="nav-item">
            <a href="<%= dashboard_parents_path %>" class="nav-link"><i class="fas fa-angle-right"></i>Parents</a>
          </li>
          <li class="nav-item">
            <a href="index5.html" class="nav-link"><i class="fas fa-angle-right"></i>Teachers</a>
          </li>
        </ul>
      </li>
      <li class="nav-item sidebar-nav-item">
        <a href="#" class="nav-link"><i class="flaticon-classmates"></i><span>Students</span></a>
        <ul class="nav sub-group-menu">
          <li class="nav-item">
            <a href="<%= students_path %>" class="nav-link"><i class="fas fa-angle-right"></i>All Student</a>
          </li>
          <li class="nav-item">
          </li>
          <li class="nav-item">
            <a href="<%= new_student_path %>" class="nav-link"><i class="fas fa-angle-right"></i>Add student</a>
          </li>
          <li class="nav-item">
            <a href="student-promotion.html" class="nav-link"><i class="fas fa-angle-right"></i>Student Promotion</a>
          </li>
        </ul>
      </li>
      <li class="nav-item sidebar-nav-item">
        <a href="#" class="nav-link"><i class="flaticon-multiple-users-silhouette"></i><span>Teachers</span></a>
        <ul class="nav sub-group-menu">
          <li class="nav-item">
            <a href="<%= teachers_path %>" class="nav-link"><i class="fas fa-angle-right"></i>All Teachers</a>
          </li>
          <li class="nav-item">
            <a href="<%= new_teacher_path %>" class="nav-link"><i class="fas fa-angle-right"></i>Add Teacher</a>
          </li>
          <li class="nav-item">
            <a href="teacher-payment.html" class="nav-link"><i class="fas fa-angle-right"></i>Payment</a>
          </li>
        </ul>
      </li>
      <li class="nav-item sidebar-nav-item">
        <a href="#" class="nav-link"><i class="flaticon-couple"></i><span>Parents</span></a>
        <ul class="nav sub-group-menu">
          <li class="nav-item">
            <a href="<%= parents_path %>" class="nav-link"><i class="fas fa-angle-right"></i>All Parents</a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link"><i class="fas fa-angle-right"></i>Parents Details</a>
          </li>
          <li class="nav-item">
            <a href="<%= new_parent_path %>" class="nav-link"><i class="fas fa-angle-right"></i>Add Parent</a>
          </li>
        </ul>
      </li>
      <li class="nav-item sidebar-nav-item">
        <a href="#" class="nav-link"><i class="flaticon-books"></i><span>books</span></a>
        <ul class="nav sub-group-menu">
          <li class="nav-item">
            <a href="<%= books_path %>" class="nav-link"><i class="fas fa-angle-right"></i>All Book</a>
          </li>
          <li class="nav-item">
            <a href=" <%= new_book_path %>" class="nav-link"><i class="fas fa-angle-right"></i>Add New Book</a>
          </li>
        </ul>
      </li>
      <li class="nav-item sidebar-nav-item">
        <a href="#" class="nav-link"><i class="flaticon-technological"></i><span>Acconunt</span></a>
        <ul class="nav sub-group-menu">
          <li class="nav-item">
            <a href="all-fees.html" class="nav-link"><i class="fas fa-angle-right"></i>All Fees Collection</a>
          </li>
          <li class="nav-item">
            <a href="all-expense.html" class="nav-link"><i class="fas fa-angle-right"></i>Expenses</a>
          </li>
          <li class="nav-item">
            <a href="add-expense.html" class="nav-link"><i class="fas fa-angle-right"></i>Add Expenses</a>
          </li>
        </ul>
      </li>
      <li class="nav-item sidebar-nav-item">
        <a href="#" class="nav-link"><i
                                    class="flaticon-maths-class-materials-cross-of-a-pencil-and-a-ruler"></i><span>Class</span></a>
        <ul class="nav sub-group-menu">
          <li class="nav-item">
            <a href="<%= classrooms_path %>" class="nav-link"><i class="fas fa-angle-right"></i>All Classes</a>
          </li>
          <li class="nav-item">
            <a href="<%= new_classroom_path %>" class="nav-link"><i class="fas fa-angle-right"></i>Add New
              Class</a>
          </li>
        </ul>
      </li>
      <li class="nav-item sidebar-nav-item">
        <a href="#" class="nav-link"><i class="flaticon-books"></i><span>subjects</span></a>
        <ul class="nav sub-group-menu">
          <li class="nav-item">
            <a href="<%= subjects_path %>" class="nav-link"><i class="fas fa-angle-right"></i>All Subject</a>
          </li>
          <li class="nav-item">
            <a href=" <%= new_subject_path %>" class="nav-link"><i class="fas fa-angle-right"></i>Add New Subject</a>
          </li>
        </ul>
        <li class="nav-item">
          <a href="class-routine.html" class="nav-link"><i class="flaticon-calendar"></i><span>Class Routine</span></a>
        </li>
        <li class="nav-item">
          <a href="student-attendence.html" class="nav-link"><i class="flaticon-checklist"></i><span>Attendence</span></a>
        </li>
        <li class="nav-item sidebar-nav-item">
          <a href="#" class="nav-link"><i class="flaticon-shopping-list"></i><span>Exam</span></a>
          <ul class="nav sub-group-menu">
            <li class="nav-item">
              <a href="exam-schedule.html" class="nav-link"><i class="fas fa-angle-right"></i>Exam Schedule</a>
            </li>
            <li class="nav-item">
              <a href="exam-grade.html" class="nav-link"><i class="fas fa-angle-right"></i>Exam Grades</a>
            </li>
          </ul>
        </li>
        <li class="nav-item sidebar-nav-item">
          <a href="#" class="nav-link"><i class="flaticon-books"></i><span>stages</span></a>
          <ul class="nav sub-group-menu">
            <li class="nav-item">
              <a href="<%= stages_path %>" class="nav-link"><i class="fas fa-angle-right"></i>All Stages</a>
            </li>
          </ul>
        </li>
        <li class="nav-item sidebar-nav-item">
          <a href="#" class="nav-link"><i class="flaticon-books"></i><span>Buses</span></a>
          <ul class="nav sub-group-menu">
            <li class="nav-item">
              <a href="<%= buses_path %>" class="nav-link"><i class="fas fa-angle-right"></i>All Buses</a>
            </li>
            <li class="nav-item">
              <a href=" <%= new_bus_path %>" class="nav-link"><i class="fas fa-angle-right"></i>Add New Bus</a>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <a href="hostel.html" class="nav-link"><i class="flaticon-bed"></i><span>Hostel</span></a>
        </li>
        <li class="nav-item">
          <a href="notice-board.html" class="nav-link"><i class="flaticon-script"></i><span>Notice</span></a>
        </li>
        <li class="nav-item">
          <a href="messaging.html" class="nav-link"><i class="flaticon-chat"></i><span>Messeage</span></a>
        </li>
        <li class="nav-item sidebar-nav-item">
          <a href="#" class="nav-link"><i class="flaticon-menu-1"></i><span>UI Elements</span></a>
          <ul class="nav sub-group-menu">
            <li class="nav-item">
              <a href="notification-alart.html" class="nav-link"><i class="fas fa-angle-right"></i>Alart</a>
            </li>
            <li class="nav-item">
              <a href="button.html" class="nav-link"><i class="fas fa-angle-right"></i>Button</a>
            </li>
            <li class="nav-item">
              <a href="grid.html" class="nav-link"><i class="fas fa-angle-right"></i>Grid</a>
            </li>
            <li class="nav-item">
              <a href="modal.html" class="nav-link"><i class="fas fa-angle-right"></i>Modal</a>
            </li>
            <li class="nav-item">
              <a href="progress-bar.html" class="nav-link"><i class="fas fa-angle-right"></i>Progress Bar</a>
            </li>
            <li class="nav-item">
              <a href="ui-tab.html" class="nav-link"><i class="fas fa-angle-right"></i>Tab</a>
            </li>
            <li class="nav-item">
              <a href="ui-widget.html" class="nav-link"><i class="fas fa-angle-right"></i>Widget</a>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <a href="map.html" class="nav-link"><i class="flaticon-planet-earth"></i><span>Map</span></a>
        </li>
        <li class="nav-item">
          <a href="<%= new_user_path %>" class="nav-link"><i class="flaticon-settings"></i><span>Account</span></a>
        </li>
      </ul>
    </div>
  </div>