config/routes.rb
Rails.application.routes.draw do

  #sessions
  get "/login", to: "sessions#new", as: :login
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :subjects
  resources :classrooms
  resources :books
  resources :buses
  resources :stages, only: [:index, :show, :edit]
  resources :teachers
  resources :parents
  resources :students

  #users
  get "/", to: "sessions#new"
  # get "/users/:id", to: "users#show", as: :my_profile
  # get "/my_profile", to: "users#show", as: :my_profile

  #dashboard
  get "/dashboard/parents", to: "dashboard_parents#index", as: :dashboard_parents

  get "/dashboard/students", to: "dashboard_students#index", as: :dashboard_students

  #books
  resources :books, except: [:show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :stage
  belongs_to :subject

  has_many :accounts, as: :accountable

  validates :name, presence: { :message => "لايجب أن يكون فارغا" }
  validates :name, format: { with: /\A[a-zA-Z ]+\z/, message: "مسموح باﻷحرف فقط" }
  validates :name, length: { minimum: 2, too_short: " يجب أن لا يقل عن 2 من [ الأحرف ]" }
  validates :name, length: { maximum: 15, too_long: " يجب أن لا يزيد عن 15 من [ الأحرف ]" }

  validates :address, presence: { :message => "لايجب أن يكون فارغا" }
  validates :address, format: { with: /\A[a-zA-Z0-9_]*[a-zA-Z][a-zA-Z0-9 ]*\z/, message: "مسموح باﻷحرف والأرقام فقط" }
  validates :address, length: { maximum: 70, too_long: " يجب أن لا يزيد عن 70 من [ الأحرف ]" }

  validates :gender, presence: { :message => "لايجب أن يكون فارغا" }
  validates :gender, format: { with: /\A[0-9a-zA-Z]*\z/ }
  validates :gender, length: { in: 1..10, message: "The number of characters is not valid" }, format: { with: /\A[a-zA-Z ]+\z/, message: "only allows letters" }

  validates :phone, length: { maximum: 13, too_long: " يجب أن لا يزيد عن 13 من [ الأحرف ]" }
  validates :phone, length: { minimum: 11, too_short: " يجب أن لا يقل عن 11 من [ الأحرف ]" }
  validates :phone, format: { with: /\A(?:\+?\d{1,3}\s*-?)?\(?(?:\d{3})?\)?[- ]?\d{3}[- ]?\d{4}\z/i, message: "يسمح فقط بالأرقام الموجبة بدون مسافات" }
  validates :phone, :uniqueness => { :message => "هذا الرقم مستخدم بالفعل" }

  validates :email, presence: { :message => "لايجب أن يكون فارغا" }, allow_blank: true
  validates :email, format: { with: /\A[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\z/, message: "تأكد من  الكتابه بشكل صحيح" }, allow_blank: true
  validates :email, :uniqueness => { :message => "هذا الأيميل مستخدم بالفعل" }

  validates :subject_id, presence: { :message => "لايجب أن يكون فارغا" }
  validates :stage_id, presence: { :message => "لايجب أن يكون فارغا" }

  #  validates_each :date_birth do |record, attr, value|
  #    record.errors.add(attr, 'يجب أن يكون أقل من 150 عامًا في الماضي') if value <= (Time.now.to_date - 125.years)
  # end

  #  validates_each :date_birth do |record, attr, value|
  #    record.errors.add(attr, 'لا يجب أن يكون تاريخ فى المستقبل') if value >= (Time.now.to_date )
  # end

  # validate :check_date

  def check_date
    errors.add(:date_birth, "يجب أن يكون أقل من 150 عامًا في الماضي") if date_birth <= (Time.now.to_date - 125.years)
    errors.add(:date_birth, "لا يجب أن يكون التاريخ فى المستقبل") if date_birth >= (Time.now.to_date)
  end

  # validates :cv, length: {minimum: 16, too_short: " يجب أن لا يقل عن 16 من [ الأحرف ]"}, allow_blank: true
  # validates :cv, length: {maximum: 800, too_long: " يجب أن لا يزيد عن 16 من [ الأحرف ]"}, allow_blank: true

  RELIGIONS = [["Moslim", "Moslim"], ["Chrestian", "Chrestian"]]
  GENDERS = [["male", "male"], ["femal", "femal"]]

  # validates :name, presence: { :message => "لايجب أن يكون فارغا" }
  # validates :name, format: { with: /\A[a-zA-Z ]+\z/, message: "مسموح باﻷحرف فقط" }
  # validates :name, length: { minimum: 2, too_short: " يجب أن لا يقل عن 2 من [ الأحرف ]" }
  # validates :name, length: { maximum: 15, too_long: " يجب أن لا يزيد عن 15 من [ الأحرف ]" }
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    @teacher = Teacher.all
  end

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(teacher_params)
    if @teacher.save
      redirect_to teachers_path
    else
      p @teacher.errors.messages
      render :new
    end
  end

  def show
    @teacher = Teacher.find(params[:id])
  end

  def edit
    @teacher = Teacher.find(params[:id])
  end

  def update
    @teacher = Teacher.find(params[:id])
    @teacher.update(teacher_params)
    redirect_to teachers_path
  end

  def destroy
    @teacher = Teacher.find(params[:id]).destroy!
    redirect_to teachers_path, notice: "Teacher was successfully destroyed."
  end

  def teacher_params
    return params.require(:teacher).permit(:name, :address, :gender, :religion, :phone, :email, :date_birth, :national_id, :stage_id, :subject_id)
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/create.html.erb
<h1>Teachers#create</h1>
<p>Find me in app/views/teachers/create.html.erb</p>

app/views/teachers/destroy.html.erb
<h1>Teachers#destroy</h1>
<p>Find me in app/views/teachers/destroy.html.erb</p>

app/views/teachers/edit.html.erb
<div class="dashboard-content-one">
  <!-- Breadcubs Area Start Here -->
  <div class="breadcrumbs-area">
    <h3>teachers</h3>
    <ul>
      <li>
        <a href="index.html">Home</a>
      </li>
      <li>Adit teachers</li>
    </ul>
  </div>
  <!-- Breadcubs Area End Here -->
  <!-- Add New Teacher Area Start Here -->
  <div class="card height-auto">
    <div class="card-body">
      <div class="heading-layout1">
        <div class="item-title">
          <h3>Adit teachers</h3>
        </div>
        <div class="dropdown">
          <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">...</a>
          <div class="dropdown-menu dropdown-menu-right">
            <a class="dropdown-item" href="#"><i class="fas fa-times text-orange-red"></i>Close</a>
            <a class="dropdown-item" href="#"><i class="fas fa-cogs text-dark-pastel-green"></i>Edit</a>
            <a class="dropdown-item" href="#"><i class="fas fa-redo-alt text-orange-peel"></i>Refresh</a>
          </div>
        </div>
      </div>
      <%= form_with model: @teacher do |f| %>
        <div class="row">
          <div class="col-xl-3 col-lg-6 col-12 form-group">
            <%= f.label :name, " Name" %>
            <%= f.text_field :name, required: true, class: "form-control" %>
            <% if @teacher.errors.messages[:name].present? %>
              <% @teacher.errors.messages[:name].each do |mass| %>
                <span class="valid-mass"><%= mass %></span>
              <% end %>
            <% end %>
          </div>
          <div class="col-xl-3 col-lg-6 col-12 form-group">
            <%= f.label :address, "Address" %>
            <%= f.text_field :address, required: true, class: "form-control" %>
            <% if @teacher.errors.messages[:address].present? %>
              <% @teacher.errors.messages[:address].each do |mass| %>
                <span class="valid-mass"><%= mass %></span>
              <% end %>
            <% end %>
          </div>
          <div class="col-xl-3 col-lg-6 col-12 form-group" >
            <%= f.label :gender, "Gender" %>
            <%= f.select("gender", Teacher::GENDERS, {}, { class: "form-control select2 select2-container select2-container--default select2-container--below" }) %>
          </div>
          <div class="col-xl-3 col-lg-6 col-12 form-group" >
            <%= f.label :religion, "Religion" %>
            <%= f.select("religion", Teacher::RELIGIONS, {}, { class: "form-control select2 select2-container select2-container--default select2-container--below" }) %>
          </div>
          <div class="col-xl-3 col-lg-6 col-12 form-group">
            <%= f.label :phone, "Phone" %>
            <%= f.text_field :phone, required: true, class: "form-control" %>
            <% if @teacher.errors.messages[:phone].present? %>
              <% @teacher.errors.messages[:phone].each do |mass| %>
                <span class="valid-mass"><%= mass %></span>
              <% end %>
            <% end %>
          </div>
          <div class="col-xl-3 col-lg-6 col-12 form-group">
            <%= f.label :email, "Email" %>
            <%= f.text_field :email, required: true, class: "form-control" %>
            <% if @teacher.errors.messages[:email].present? %>
              <% @teacher.errors.messages[:email].each do |mass| %>
                <span class="valid-mass"><%= mass %></span>
              <% end %>
            <% end %>
          </div>
          <div class="col-xl-3 col-lg-6 col-12 form-group">
            <%= f.label :date_birth, "Date_Birth" %>
            <%= f.text_field :date_birth, required: true, class: "form-control" %>
            <% if @teacher.errors.messages[:date_birth].present? %>
              <% @teacher.errors.messages[:date_birth].each do |mass| %>
                <span class="valid-mass"><%= mass %></span>
              <% end %>
            <% end %>
          </div>
          <div class="col-xl-3 col-lg-6 col-12 form-group">
            <%= f.label :national_id, "National_ID" %>
            <%= f.text_field :national_id, required: true, class: "form-control" %>
            <% if @teacher.errors.messages[:national_id].present? %>
              <% @teacher.errors.messages[:national_id].each do |mass| %>
                <span class="valid-mass"><%= mass %></span>
              <% end %>
            <% end %>
          </div>
          <div class="col-xl-3 col-lg-6 col-12 form-group" data-select2-id="14">
            <%= f.label :stage_id, "Name Stage" %>
            <%= f.select("stage_id", Stage.all.map { |s| [s.name, s.id] }, {}, { class: "form-control select2 select2-container select2-container--default select2-container--below" }) %>
            <% if @teacher.errors.messages[:stage_id].present? %>
              <% @teacher.errors.messages[:stage_id].each do |mass| %>
                <%= mass %>
              <% end %>
            <% end %>
          </div>
          <div class="col-xl-3 col-lg-6 col-12 form-group" data-select2-id="14">
            <%= f.label :subject_id, "Name Subject" %>
            <%= f.select("stage_id", Subject.all.map { |s| [s.name, s.id] }, {}, { class: "form-control select2 select2-container select2-container--default select2-container--below" }) %>
            <% if @teacher.errors.messages[:subject_id].present? %>
              <% @teacher.errors.messages[:subject_id].each do |mass| %>
                <%= mass %>
              <% end %>
            <% end %>
          </div>
          <div class="col-md-6 d-none d-xl-block">
          </div>
          <div class="col-lg-6 col-12 form-group">
            <%= f.label :cv, "cv" %>
            <%= f.text_area :cv, required: true, class: "textarea form-control" %>
          </div>
          <div class="col-lg-6 col-12 form-group mg-t-30">
            <label class="text-dark-medium">Upload teacher Photo (150px X 150px)</label>
            <input type="file" class="form-control-file">
          </div>
          <div class="col-12 form-group mg-t-8">
            <button type="submit" class="btn-fill-lg btn-gradient-yellow btn-hover-bluedark">Save</button>
            <button type="reset" class="btn-fill-lg bg-blue-dark btn-hover-yellow">Reset</button>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <!-- Add New Teacher Area End Here -->
</div>

app/views/teachers/index.html.erb
<div class="dashboard-content-one">
  <!-- Breadcubs Area Start Here -->
  <div class="breadcrumbs-area">
    <h3>teacher</h3>
    <ul>
      <li>
        <a href="index.html">Home</a>
      </li>
      <li>All Library Teacher</li>
    </ul>
  </div>
  <!-- Breadcubs Area End Here -->
  <!-- Teacher Table Area Start Here -->
  <div class="card height-auto">
    <div class="card-body">
      <div class="heading-layout1">
        <div class="item-title">
          <h3>All Teacher Data</h3>
        </div>
        <div class="dropdown">
          <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">...</a>
          <div class="dropdown-menu dropdown-menu-right">
            <a class="dropdown-item" href="#"><i class="fas fa-times text-orange-red"></i>Close</a>
            <a class="dropdown-item" href="#"><i class="fas fa-cogs text-dark-pastel-green"></i>Edit</a>
            <a class="dropdown-item" href="#"><i class="fas fa-redo-alt text-orange-peel"></i>Refresh</a>
          </div>
        </div>
      </div>
      <form class="mg-b-20">
        <div class="row gutters-8">
          <div class="col-3-xxxl col-xl-3 col-lg-3 col-12 form-group">
            <input type="text" placeholder="Search by ID ..." class="form-control">
          </div>
          <div class="col-4-xxxl col-xl-4 col-lg-3 col-12 form-group">
            <input type="text" placeholder="Search by Name ..." class="form-control">
          </div>
          <div class="col-4-xxxl col-xl-3 col-lg-3 col-12 form-group">
            <input type="text" placeholder="Search by Phone ..." class="form-control">
          </div>
          <div class="col-1-xxxl col-xl-2 col-lg-3 col-12 form-group">
            <button type="submit" class="fw-btn-fill btn-gradient-yellow">SEARCH</button>
          </div>
        </div>
      </form>
      <div class="table-responsive">
        <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper no-footer">
          <table class="table display data-table text-nowrap dataTable no-footer" id="DataTables_Table_0" role="grid">
            <thead>
              <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Photo: activate to sort column ascending" style="width: 43px;">ID</th>
              <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending" style="width: 155px;">Name</th>
              <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Gender: activate to sort column ascending" style="width: 130px;">Address</th>
              <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Class: activate to sort column ascending" style="width: 40px;">Gender</th>
              <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Section: activate to sort column ascending" style="width: 55px;">religion</th>
              <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Parents: activate to sort column ascending" style="width: 96px;">Phone</th>
              <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Address: activate to sort column ascending" style="width: 134px;">Email</th>
              <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Date Of Birth: activate to sort column ascending" style="width: 93px;">Date_Birth</th>
              <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Phone: activate to sort column ascending" style="width: 101px;">National_ID</th>
              <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Phone: activate to sort column ascending" style="width: 101px;">Stage Name</th>
              <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Phone: activate to sort column ascending" style="width: 101px;">Subject Name</th>
              <th class="sorting_disabled" rowspan="1" colspan="1" aria-label="" style="width: 48px;"></th>
            </tr>
          </thead>
          <tbody>
            <% Teacher.all.each do |teacher| %>
              <tr role="row" class="odd">
                <td> <%= teacher.id %></td>
                <td><%= teacher.name %></td>
                <td><%= teacher.address %></td>
                <td><%= teacher.gender %></td>
                <td><%= teacher.religion %></td>
                <td><%= teacher.phone %></td>
                <td><%= teacher.email %></td>
                <td><%= teacher.date_birth %></td>
                <td><%= teacher.national_id %></td>
                <td><%= teacher.stage.name %></td>
                <td><%= teacher.subject.name %></td>
                <td>
                  <div class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                      <span class="flaticon-more-button-of-three-dots"></span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                      <i class="icon_edit fas fa-cogs  text-dark-pastel-green"></i><a class="dropdown-item edit" href="<%= edit_teacher_path(teacher.id) %>">Edit</a>
                      <i class="icon_show far fa-eye  text-dark-pastel-green"></i><a class="dropdown-item edit" href="<%= teacher_path(teacher.id) %> %>">Show</a>
                      <i class=" icon_delete far fa-trash-alt "></i><%= button_to "Delete", teacher_path(teacher.id), method: "delete",  class: "delete", data: { confirm: "Are you sure you want to delete?" } %>
                    </div>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="dataTables_paginate paging_simple_numbers" id="DataTables_Table_0_paginate"><a class="paginate_button previous disabled" aria-controls="DataTables_Table_0" data-dt-idx="0" tabindex="0" id="DataTables_Table_0_previous">Previous</a><span><a class="paginate_button current" aria-controls="DataTables_Table_0" data-dt-idx="1" tabindex="0">1</a><a class="paginate_button " aria-controls="DataTables_Table_0" data-dt-idx="2" tabindex="0">2</a></span><a class="paginate_button next" aria-controls="DataTables_Table_0" data-dt-idx="3" tabindex="0" id="DataTables_Table_0_next">Next</a></div>
      </div>
    </div>
  </div>
</div>
<!-- Teacher Table Area End Here -->
</div>

app/views/teachers/new.html.erb
<div class="dashboard-content-one">
  <!-- Breadcubs Area Start Here -->
  <div class="breadcrumbs-area">
    <h3>Library</h3>
    <ul>
      <li>
        <a href="index.html">Home</a>
      </li>
      <li>Add New Teacher</li>
    </ul>
  </div>
  <!-- Breadcubs Area End Here -->
  <!-- Add New Teacher Area Start Here -->
  <div class="card height-auto">
    <div class="card-body">
      <div class="heading-layout1">
        <div class="item-title">
          <h3>Add New Teacher</h3>
        </div>
        <div class="dropdown">
          <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">...</a>
          <div class="dropdown-menu dropdown-menu-right">
            <a class="dropdown-item" href="#"><i class="fas fa-times text-orange-red"></i>Close</a>
            <a class="dropdown-item" href="#"><i class="fas fa-cogs text-dark-pastel-green"></i>Edit</a>
            <a class="dropdown-item" href="#"><i class="fas fa-redo-alt text-orange-peel"></i>Refresh</a>
          </div>
        </div>
      </div>
      <%= form_with model: @teacher do |f| %>
        <div class="row">
          <div class="col-xl-3 col-lg-6 col-12 form-group">
            <%= f.label :name, "Teacher Name" %>
            <%= f.text_field :name, required: true, class: "form-control" %>
            <% if @teacher.errors.messages[:name].present? %>
              <% @teacher.errors.messages[:name].each do |mess| %>
                <span class="valid-mess"><%= mess %></span><br>
              <% end %>
            <% end %>
          </div>
          <div class="col-xl-3 col-lg-6 col-12 form-group">
            <%= f.label :address, "Address" %>
            <%= f.text_field :address, required: true, class: "form-control" %>
            <% if @teacher.errors.messages[:address].present? %>
              <% @teacher.errors.messages[:address].each do |mess| %>
                <span class="valid-mess"><%= mess %></span><br>
              <% end %>
            <% end %>
          </div>
          <div class="col-xl-3 col-lg-6 col-12 form-group">
            <%= f.label :gender, "Gender" %>
            <%= f.text_field :gender, required: true, class: "form-control" %>
            <% if @teacher.errors.messages[:gender].present? %>
              <% @teacher.errors.messages[:gender].each do |mess| %>
                <span class="valid-mess"><%= mess %></span><br>
              <% end %>
            <% end %>
          </div>
          <div class="col-xl-3 col-lg-6 col-12 form-group">
            <%= f.label :religion, "Religion" %>
            <%= f.text_field :religion, required: true, class: "form-control" %>
            <% if @teacher.errors.messages[:religion].present? %>
              <% @teacher.errors.messages[:religion].each do |mess| %>
                <span class="valid-mess"><%= mess %></span><br>
              <% end %>
            <% end %>
          </div>
          <div class="col-xl-3 col-lg-6 col-12 form-group">
            <%= f.label :phone, "Phone" %>
            <%= f.text_field :phone, required: true, class: "form-control" %>
            <% if @teacher.errors.messages[:phone].present? %>
              <% @teacher.errors.messages[:phone].each do |mess| %>
                <span class="valid-mess"><%= mess %></span><br>
              <% end %>
            <% end %>
          </div>
          <div class="col-xl-3 col-lg-6 col-12 form-group">
            <%= f.label :email, "Email" %>
            <%= f.text_field :email, class: "form-control" %>
            <% if @teacher.errors.messages[:email].present? %>
              <% @teacher.errors.messages[:email].each do |mess| %>
                <span class="valid-mess"><%= mess %></span><br>
              <% end %>
            <% end %>
          </div>
          <div class="col-xl-3 col-lg-6 col-12 form-group">
            <%= f.label :date_birth, "date_Birth" %>
            <%= f.text_field :date_birth, required: true, class: "form-control" %>
            <% if @teacher.errors.messages[:date_birth].present? %>
              <% @teacher.errors.messages[:date_birth].each do |mess| %>
                <span class="valid-mess"><%= mess %></span><br>
              <% end %>
            <% end %>
          </div>
          <div class="col-xl-3 col-lg-6 col-12 form-group">
            <%= f.label :national_id, "National_id" %>
            <%= f.text_field :national_id, required: true, class: "form-control" %>
            <% if @teacher.errors.messages[:national_id].present? %>
              <% @teacher.errors.messages[:national_id].each do |mess| %>
                <span class="valid-mess"><%= mess %></span><br>
              <% end %>
            <% end %>
          </div>
          <div class="col-xl-3 col-lg-6 col-12 form-group" data-select2-id="14">
            <%= f.label :stage_id, "Name Stage" %>
            <%= f.select("stage_id", Stage.all.map { |s| [s.name, s.id] }, {}, { class: "form-control select2 select2-container select2-container--default select2-container--below" }) %>
            <% if @teacher.errors.messages[:stage_id].present? %>
              <% @teacher.errors.messages[:stage_id].each do |mass| %>
                <%= mass %>
              <% end %>
            <% end %>
          </div>
          <div class="col-xl-3 col-lg-6 col-12 form-group" data-select2-id="14">
            <%= f.label :subject_id, "Subject Name" %>
            <%= f.select("subject_id", Subject.all.map { |p| [p.name, p.id] }, {}, { class: "form-control select2 select2-container select2-container--default select2-container--below" }) %>
            <% if @teacher.errors.messages[:subject_id].present? %>
              <% @teacher.errors.messages[:subject_id].each do |mass| %>
                <%= mass %>
              <% end %>
            <% end %>
          </div>
          <div class="col-12 form-group mg-t-8">
            <button type="submit" class="btn-fill-lg btn-gradient-yellow btn-hover-bluedark">Save</button>
            <button type="reset" class="btn-fill-lg bg-blue-dark btn-hover-yellow">Reset</button>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <!-- Add New Teacher Area End Here -->
</div>

app/views/teachers/show.html.erb
<h1>Teachers#show</h1>
<p>Find me in app/views/teachers/show.html.erb</p>

app/views/teachers/update.html.erb
<h1>Teachers#update</h1>
<p>Find me in app/views/teachers/update.html.erb</p>