config/routes.rb
Rails.application.routes.draw do

  #sessions
  get "/login", to: "sessions#new", as: :login
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :subjects
  resources :classrooms
  resources :books
  resources :buses
  resources :stages, only: [:index, :show, :edit]
  resources :teachers
  resources :parents
  resources :students

  #users
  get "/", to: "sessions#new"
  # get "/users/:id", to: "users#show", as: :my_profile
  # get "/my_profile", to: "users#show", as: :my_profile

  #dashboard
  get "/dashboard/parents", to: "dashboard_parents#index", as: :dashboard_parents

  get "/dashboard/students", to: "dashboard_students#index", as: :dashboard_students

  #books
  resources :books, except: [:show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/stage.rb
class Stage < ApplicationRecord
  has_many :subjects
  has_many :students
  has_many :techers

  validates :name, presence: { :message => "لايجب أن يكون فارغا" }
  validates :name, format: { with: /\A[a-zA-Z ]+\z/, message: "مسموح باﻷحرف فقط" }
  validates :name, length: { minimum: 2, too_short: " يجب أن لا يقل عن 2 من [ الأحرف ]" }
  validates :name, length: { maximum: 70, too_long: " يجب أن لا يزيد عن 70 من [ الأحرف ]" }
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  def index
    @stages = Stage.all
  end

  # def new
  #   @stage = Stage.new
  # end

  # def create
  #   @stage = Stage.new
  #   @stage.attributes = stage_params
  #   if @stage.save
  #     redirect_to stages_path
  #   else
  #     render :new
  #   end
  # end

  def show
    @stage = Stage.find(params[:id])
  end

  def edit
    @stage = Stage.find(params[:id])
  end

  def update
    stage = Stage.find(params[:id])
    if stage.update(stage_params)
      redirect_to stages_path, notice: "Stage was successfully updated."
    else
      render :edit
    end
  end

  # def destroy
  #   stage = Stage.find(params[:id])
  #   if stage.destroy
  #     flash[:notice] = "The parent has been deleted"
  #   else
  #     flash[:error] = "Your patient has been deleted"
  #   end

  #   redirect_to stages_path
  # end

  def stage_params
    return params.require(:stage).permit(:name)
  end
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/views/stages/create.html.erb
<h1>Stages#create</h1>
<p>Find me in app/views/stages/create.html.erb</p>

app/views/stages/destroy.html.erb
<h1>Stages#destroy</h1>
<p>Find me in app/views/stages/destroy.html.erb</p>

app/views/stages/edit.html.erb
<div class="dashboard-content-one">
    <!-- Breadcubs Area Start Here -->
    <div class="breadcrumbs-area">
        <h3>Library</h3>
        <ul>
            <li>
                <a href="index.html">Home</a>
            </li>
            <li>edit  stage</li>
        </ul>
    </div>
    <!-- Breadcubs Area End Here -->
    <!-- edit  stage Area Start Here -->
    <div class="card height-auto">
        <div class="card-body">
            <div class="heading-layout1">
                <div class="item-title">
                    <h3>edit  stage</h3>
                </div>
                <div class="dropdown">
                    <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">...</a>

                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" href="#"><i class="fas fa-times text-orange-red"></i>Close</a>
                        <a class="dropdown-item" href="#"><i class="fas fa-cogs text-dark-pastel-green"></i>Edit</a>
                        <a class="dropdown-item" href="#"><i class="fas fa-redo-alt text-orange-peel"></i>Refresh</a>
                    </div>
                </div>
            </div>

                <%= form_with model: @stage do |f| %>

                <div class="row">

                    <div class="col-xl-3 col-lg-4 col-12 form-group">

                    <%= f.label :name, "Stage Name" %>
                    <%= f.text_field :name, required: true, class: "form-control" %>
                    </div>
                    
                    <div class="col-12 form-group mg-t-8">
                    
                        <button type="submit" class="btn-fill-lg btn-gradient-yellow btn-hover-bluedark">Save</button>
                        <button type="reset" class="btn-fill-lg bg-blue-dark btn-hover-yellow">Reset</button>
                    </div>

                </div>
        
                <% end %>
        </div>
    </div>
    <!-- edit  stage Area End Here -->
    
</div>

app/views/stages/index.html.erb
<div class="dashboard-content-one">
  <!-- Breadcubs Area Start Here -->
  <div class="breadcrumbs-area">
    <h3>stages</h3>
    <ul>
      <li>
        <a href="index.html">Home</a>
      </li>
      <li>All Library stages</li>
    </ul>
  </div>
  <!-- Breadcubs Area End Here -->
  <!-- Teacher Table Area Start Here -->
  <div class="card height-auto">
    <div class="card-body">
      <div class="heading-layout1">
        <div class="item-title">
          <h3>All stages Data</h3>
        </div>
        <div class="dropdown">
          <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">...</a>
          <div class="dropdown-menu dropdown-menu-right">
            <a class="dropdown-item" href="#"><i class="fas fa-times text-orange-red"></i>Close</a>
            <a class="dropdown-item" href="#"><i class="fas fa-cogs text-dark-pastel-green"></i>Edit</a>
            <a class="dropdown-item" href="#"><i class="fas fa-redo-alt text-orange-peel"></i>Refresh</a>
          </div>
        </div>
      </div>
      <form class="mg-b-20">
        <div class="row gutters-8">
          <div class="col-3-xxxl col-xl-3 col-lg-3 col-12 form-group">
            <input type="text" placeholder="Search by ID ..." class="form-control">
          </div>
          <div class="col-4-xxxl col-xl-4 col-lg-3 col-12 form-group">
            <input type="text" placeholder="Search by Name ..." class="form-control">
          </div>
          <div class="col-4-xxxl col-xl-3 col-lg-3 col-12 form-group">
            <input type="text" placeholder="Search by Phone ..." class="form-control">
          </div>
          <div class="col-1-xxxl col-xl-2 col-lg-3 col-12 form-group">
            <button type="submit" class="fw-btn-fill btn-gradient-yellow">SEARCH</button>
          </div>
        </div>
      </form>
      <div class="table-responsive">
        <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper no-footer">
          <table class="table display data-table text-nowrap dataTable no-footer" id="DataTables_Table_0" role="grid">
            <thead>
              <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending" style="width: 119px; text-align:center;">ID</th>
              <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending" style="width: 115px;  " >Name</th>
              <th class="sorting_disabled" rowspan="1" colspan="1" aria-label="" style="width: 48px;"></th>
            </tr>
          </thead>
          <tbody>
            <% Stage.all.each do |stage| %>
              <tr role="row" class="odd">
                <td class="sorting_1">
                  <div class="form-check">
                    <input type="checkbox" class="form-check-input">
                    <label class="form-check-label"><%= stage.id %></label>
                  </div>
                </td>
                <td><%= stage.name %></td>
                <td>
                  <div class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                      <span class="flaticon-more-button-of-three-dots"></span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                      <i class="icon_edit fas fa-cogs  text-dark-pastel-green"></i><a class="dropdown-item edit" href="<%= edit_stage_path(stage.id) %>">Edit</a>
                      <i class="icon_show far fa-eye  text-dark-pastel-green"></i><a class="dropdown-item edit" href="<%= stage_path(stage.id) %> %>">Show</a>
                      <i class=" icon_delete far fa-trash-alt "></i><%= button_to "Delete", stage_path(stage.id), method: "delete",  class: "delete", data: { confirm: "Are you sure you want to delete?" } %>
                    </div>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="dataTables_paginate paging_simple_numbers" id="DataTables_Table_0_paginate"><a class="paginate_button previous disabled" aria-controls="DataTables_Table_0" data-dt-idx="0" tabindex="0" id="DataTables_Table_0_previous">Previous</a><span><a class="paginate_button current" aria-controls="DataTables_Table_0" data-dt-idx="1" tabindex="0">1</a><a class="paginate_button " aria-controls="DataTables_Table_0" data-dt-idx="2" tabindex="0">2</a></span><a class="paginate_button next" aria-controls="DataTables_Table_0" data-dt-idx="3" tabindex="0" id="DataTables_Table_0_next">Next</a></div>
      </div>
    </div>
  </div>
</div>
<!-- Teacher Table Area End Here -->
</div>

app/views/stages/show.html.erb
<div class="dashboard-content-one">
            <!-- Breadcubs Area Start Here -->
            <div class="breadcrumbs-area">
                <h3>stages</h3>
                <ul>
                    <li>
                        <a href="index.html">Home</a>
                    </li>
                    <li>stages Details</li>
                </ul>
            </div>
            <!-- Breadcubs Area End Here -->
            <!-- Student Details Area Start Here -->
            <div class="card height-auto">
                <div class="card-body">
                    <div class="heading-layout1">
                     
                        <div class="dropdown">
                            <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">...</a>
    
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item" href="#"><i class="fas fa-times text-orange-red"></i>Close</a>
                                <a class="dropdown-item" href="#"><i class="fas fa-cogs text-dark-pastel-green"></i>Edit</a>
                                <a class="dropdown-item" href="#"><i class="fas fa-redo-alt text-orange-peel"></i>Refresh</a>
                            </div>
                            
                        </div>
                    </div>
                    <div class="single-info-details">
                        <div class="item-img">

                            <img src="/img/figure/first_gride.jpg" alt="student">
                        </div>
                        
                        <div class="item-content">
                            <div class="header-inline item-header">
                                <h3 class="text-dark-medium font-medium"> </span></h3>
                                <div class="header-elements">
                                    <ul>
                                        <li><a href="<%= edit_stage_path(@stage.id) %>"><i class="far fa-edit"></i></a></li>
                                        <li><a href="#"><i class="fas fa-print"></i></a></li>
                                        <li><a href="#"><i class="fas fa-download"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="info-table table-responsive">
                                <table class="table text-nowrap">
                                    <tbody>
                                        <tr>
                                            <td>Name:</td>
                                            <td class="font-medium text-dark-medium"><%= @stage.name %></td>
                                        </tr>
                                    </tbody>
                                </table>
                                
                            </div>
                            <hr>
                                
                        </div>
                    </div>

                </div>
            </div>
            <!-- Student Details Area End Here -->
            
        </div>

app/views/stages/update.html.erb
<h1>Stages#update</h1>
<p>Find me in app/views/stages/update.html.erb</p>