config/routes.rb
Rails.application.routes.draw do

  #sessions
  get "/login", to: "sessions#new", as: :login
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :subjects
  resources :classrooms
  resources :books
  resources :buses
  resources :stages, only: [:index, :show, :edit]
  resources :teachers
  resources :parents
  resources :students

  #users
  get "/", to: "sessions#new"
  # get "/users/:id", to: "users#show", as: :my_profile
  # get "/my_profile", to: "users#show", as: :my_profile

  #dashboard
  get "/dashboard/parents", to: "dashboard_parents#index", as: :dashboard_parents

  get "/dashboard/students", to: "dashboard_students#index", as: :dashboard_students

  #books
  resources :books, except: [:show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/buses_controller.rb
class BusesController < ApplicationController
  def index
    @buss = Bus.all
  end

  def new
    @bus = Bus.new
  end

  def create
    @bus = Bus.new(bus_params)
    if @bus.save
      redirect_to buses_path, notice: "Bus was successfully created."
    else
      redirect_to new_bus_path
    end
  end

  # def show

  #     @bus = bus.find(params[:id])

  # end

  def edit
    @bus = Bus.find(params[:id])
  end

  def update
    @bus = Bus.find(params[:id])
    if @bus.update!(bus_params)
      redirect_to buses_path, notice: "bus was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @bus = Bus.find(params[:id]).destroy!
    redirect_to buses_path, notice: "bus was successfully destroyed."
  end

  def bus_params
    return params.require(:bus).permit(:model, :driver, :bus_number, :color)
  end
end

app/helpers/buses_helper.rb
module BusesHelper
end

app/views/buses/create.html.erb
<h1>Buses#create</h1>
<p>Find me in app/views/buses/create.html.erb</p>

app/views/buses/destroy.html.erb
<h1>Buses#destroy</h1>
<p>Find me in app/views/buses/destroy.html.erb</p>

app/views/buses/edit.html.erb
<div class="dashboard-content-one">
    <!-- Breadcubs Area Start Here -->
    <div class="breadcrumbs-area">
        <h3>Library</h3>
        <ul>
            <li>
                <a href="index.html">Home</a>
            </li>
            <li>Add New bus</li>
        </ul>
    </div>
    <!-- Breadcubs Area End Here -->
    <!-- Add New bus Area Start Here -->
    <div class="card height-auto">
        <div class="card-body">
            <div class="heading-layout1">
                <div class="item-title">
                    <h3>Add New bus</h3>
                </div>
                <div class="dropdown">
                    <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">...</a>

                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" href="#"><i class="fas fa-times text-orange-red"></i>Close</a>
                        <a class="dropdown-item" href="#"><i class="fas fa-cogs text-dark-pastel-green"></i>Edit</a>
                        <a class="dropdown-item" href="#"><i class="fas fa-redo-alt text-orange-peel"></i>Refresh</a>
                    </div>
                </div>
            </div>

                <%= form_with model: @bus do |f| %>

                <div class="row">

                    <div class="col-xl-3 col-lg-4 col-12 form-group">

                    <%= f.label :model, "Bus model" %>
                    <%= f.text_field :model, required: true, class: "form-control" %>
                    </div>
                        <div class="col-xl-3 col-lg-4 col-12 form-group">

                    <%= f.label :driver, "Driver" %>
                    <%= f.text_field :driver, required: true, class: "form-control" %>
                    </div>
                        <div class="col-xl-3 col-lg-4 col-12 form-group">

                    <%= f.label :bus_number, "Bus_Number" %>
                    <%= f.text_field :bus_number, required: true, class: "form-control" %>
                    </div>
                        
                        <div class="col-xl-3 col-lg-4 col-12 form-group">

                    <%= f.label :color, "Color" %>
                    <%= f.text_field :color, required: true, class: "form-control" %>
                    
                    </div>
                    <div class="col-12 form-group mg-t-8">
                    
                        <button type="submit" class="btn-fill-lg btn-gradient-yellow btn-hover-bluedark">Save</button>
                        <button type="reset" class="btn-fill-lg bg-blue-dark btn-hover-yellow">Reset</button>
                    </div>

                </div>
        
                <% end %>
        </div>
    </div>
    <!-- Add New bus Area End Here -->
    
</div>

app/views/buses/index.html.erb
<div class="dashboard-content-one">
  <!-- Breadcubs Area Start Here -->
  <div class="breadcrumbs-area">
    <h3>buses</h3>
    <ul>
      <li>
        <a href="index.html">Home</a>
      </li>
      <li>All Library buses</li>
    </ul>
  </div>
  <!-- Breadcubs Area End Here -->
  <!-- Teacher Table Area Start Here -->
  <div class="card height-auto">
    <div class="card-body">
      <div class="heading-layout1">
        <div class="item-title">
          <h3>All buses Data</h3>
        </div>
        <div class="dropdown">
          <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">...</a>
          <div class="dropdown-menu dropdown-menu-right">
            <a class="dropdown-item" href="#"><i class="fas fa-times text-orange-red"></i>Close</a>
            <a class="dropdown-item" href="#"><i class="fas fa-cogs text-dark-pastel-green"></i>Edit</a>
            <a class="dropdown-item" href="#"><i class="fas fa-redo-alt text-orange-peel"></i>Refresh</a>
          </div>
        </div>
      </div>
      <form class="mg-b-20">
        <div class="row gutters-8">
          <div class="col-3-xxxl col-xl-3 col-lg-3 col-12 form-group">
            <input type="text" placeholder="Search by ID ..." class="form-control">
          </div>
          <div class="col-4-xxxl col-xl-4 col-lg-3 col-12 form-group">
            <input type="text" placeholder="Search by Name ..." class="form-control">
          </div>
          <div class="col-4-xxxl col-xl-3 col-lg-3 col-12 form-group">
            <input type="text" placeholder="Search by Phone ..." class="form-control">
          </div>
          <div class="col-1-xxxl col-xl-2 col-lg-3 col-12 form-group">
            <button type="submit" class="fw-btn-fill btn-gradient-yellow">SEARCH</button>
          </div>
        </div>
      </form>
      <div class="table-responsive">
        <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper no-footer">
          <table class="table display data-table text-nowrap dataTable no-footer" id="DataTables_Table_0" role="grid">
            <thead>
              <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending" style="width: 119px; text-align:center;">ID</th>
              <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Gender: activate to sort column ascending" >Driver</th>
              <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Class: activate to sort column ascending" >Bus_Number</th>
              <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending" style="width: 115px;  " >Bus model</th>
              <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Section: activate to sort column ascending" >Color</th>
              <th class="sorting_disabled" rowspan="1" colspan="1" aria-label="" style="width: 48px;"></th>
            </tr>
          </thead>
          <tbody>
            <% Bus.all.each do |bus| %>
              <tr role="row" class="odd">
                <td class="sorting_1">
                  <div class="form-check">
                    <input type="checkbox" class="form-check-input">
                    <label class="form-check-label"><%= bus.id %></label>
                  </div>
                </td>
                <td><%= bus.driver %></td>
                <td><%= bus.bus_number %></td>
                <td><%= bus.model %></td>
                <td><%= bus.color %></td>
                <td>
                  <div class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                      <span class="flaticon-more-button-of-three-dots"></span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                      <i class="icon_edit fas fa-cogs  text-dark-pastel-green"></i><a class="dropdown-item edit" href="<%= edit_bus_path(bus.id) %>">Edit</a>
                      <i class="icon_show far fa-eye  text-dark-pastel-green"></i><a class="dropdown-item edit" href="<%= bus_path(bus.id) %> %>">Show</a>
                      <i class=" icon_delete far fa-trash-alt "></i><%= button_to "Delete", bus_path(bus.id), method: "delete",  class: "delete", data: { confirm: "Are you sure you want to delete?" } %>
                    </div>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="dataTables_paginate paging_simple_numbers" id="DataTables_Table_0_paginate"><a class="paginate_button previous disabled" aria-controls="DataTables_Table_0" data-dt-idx="0" tabindex="0" id="DataTables_Table_0_previous">Previous</a><span><a class="paginate_button current" aria-controls="DataTables_Table_0" data-dt-idx="1" tabindex="0">1</a><a class="paginate_button " aria-controls="DataTables_Table_0" data-dt-idx="2" tabindex="0">2</a></span><a class="paginate_button next" aria-controls="DataTables_Table_0" data-dt-idx="3" tabindex="0" id="DataTables_Table_0_next">Next</a></div>
      </div>
    </div>
  </div>
</div>
<!-- Teacher Table Area End Here -->
</div>

app/views/buses/new.html.erb
<div class="dashboard-content-one">
<!-- Breadcubs Area Start Here -->
<div class="breadcrumbs-area">
    <h3>Library</h3>
    <ul>
        <li>
            <a href="index.html">Home</a>
        </li>
        <li>Add New bus</li>
    </ul>
</div>
<!-- Breadcubs Area End Here -->
<!-- Add New bus Area Start Here -->
<div class="card height-auto">
    <div class="card-body">
        <div class="heading-layout1">
            <div class="item-title">
                <h3>Add New bus</h3>
            </div>
            <div class="dropdown">
                <a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">...</a>

                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="#"><i class="fas fa-times text-orange-red"></i>Close</a>
                    <a class="dropdown-item" href="#"><i class="fas fa-cogs text-dark-pastel-green"></i>Edit</a>
                    <a class="dropdown-item" href="#"><i class="fas fa-redo-alt text-orange-peel"></i>Refresh</a>
                </div>
            </div>
        </div>

            <%= form_with model: @bus do |f| %>

            <div class="row">

                <div class="col-xl-3 col-lg-4 col-12 form-group">

                <%= f.label :model, "Bus model" %>
                <%= f.text_field :model, required: true, class: "form-control" %>
                </div>
                    <div class="col-xl-3 col-lg-4 col-12 form-group">

                <%= f.label :driver, "Driver" %>
                <%= f.text_field :driver, required: true, class: "form-control" %>
                </div>
                    <div class="col-xl-3 col-lg-4 col-12 form-group">

                <%= f.label :bus_number, "Bus_Number" %>
                <%= f.text_field :bus_number, required: true, class: "form-control" %>
                </div>
                    
                    <div class="col-xl-3 col-lg-4 col-12 form-group">

                <%= f.label :color, "Color" %>
                <%= f.text_field :color, required: true, class: "form-control" %>
                
                </div>
                <div class="col-12 form-group mg-t-8">
                
                    <button type="submit" class="btn-fill-lg btn-gradient-yellow btn-hover-bluedark">Save</button>
                    <button type="reset" class="btn-fill-lg bg-blue-dark btn-hover-yellow">Reset</button>
                </div>

            </div>
    

            <% end %>
    </div>
</div>
<!-- Add New bus Area End Here -->

</div>

app/views/buses/show.html.erb
<h1>Buses#show</h1>
<p>Find me in app/views/buses/show.html.erb</p>

app/views/buses/update.html.erb
<h1>Buses#update</h1>
<p>Find me in app/views/buses/update.html.erb</p>